manifest:
  remotes:
    - name: krikun98
      url-base: https://github.com/krikun98
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
    - name: zmk
      remote: krikun98
      revision: mouse-pr
      import: app/west.yml
